---
title: "Socialt hållbara bostadsområden (SHB)"
author: "Samhällsanalys"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
lang: sv
format:
  html:
    include-in-header: favicon.html
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: true
    code-copy: true
---
# Socialt hållbara bostadsområden (SHB)
## Introduktion

SHB (Socialt hållbara bostadsområden) är en områdesindelning som används för att följa upp och analysera bostadsområden ur ett socialt hållbarhetsperspektiv.
SHB‑områdena definieras och namnges manuellt av kommunerna, och kan variera i geografisk avgränsning. I vissa fall kan kommuner  välja att samla glesbygd eller landsbygdsområden till större områden för att uppnå tillräcklig befolkningsstorlek för statistik och uppföljning.

Viktiga egenskaper hos SHB:

1. Geometrier tas fram manuellt
1. Namn och avgränsning bestäms lokalt

## Process

Nycklar mellan SHB och NYKO går att finna i `G:\Uppföljning och Utvärdering\shb`.
Insamlade NYKO sparas och går att finna i `G:\Samhällsanalys\GIS\grundkartor\nyko` *se till att aktuella områden läses in vid bearbetning av datan*

### Översikt

1.  Samla in SHB områden
2.  Skapa polygonlager med SHB områden

## Insamling av områden

En del SHB områden utgår från kommunernas NYKO-indelning. Tidigare användes uteslutande NYKO och alla SHB områden var således kopplade till en NYKO-kod. Det är upp till kommunerna om de vill utgå från NYKO eller om de själva vill skapa geografiska indelningar som motsvarar SHB geom att själva rita ut gränserna.

De områden som kommunerna skapar önskar vi levererade i geopackage-filer. Om vi redan har NYKO och kommunen önskar utgå från samma NYKO-indelning fungerar det även om kommunen skcikar en nyckel i förslagsvis excelformat med NYKO och SHB kopplade.

## Kriterier


## Sammanställning av områden

Områdena sammanställs till en gpkg som sedan skrivs till databaen. När alla områden slås ihop är det viktigt att kontrollera koordinatsystemen då antingen NYKO eller egna områden iband levereras med olika koordinatsystem. Sammanställ alla till sweref99.

### NYKO - SHB

### SHB områden som gpkg filer
```{r}
#| echo: false
```
### Resultat

Polygoner med SHB områden skriv till schema
```
postgis_databas_skriv_med_metadata(
  con = uppkoppling_adm("geodata"),
  inlas_sf = omrade_polygon,
  schema = "omradesindelningar",
  tabell = "shb_omraden",
  postgistabell_geo_kol = "geometry",
  postgistabell_id_kol = "omrade"
)

```

## Koppling till borutor
```
postgis_skapa_omradesnyckel_tabell_vy(
  con = uppkoppling_adm("geodata"),
  omrades_schema = "omradesindelningar",
  omrades_tabell = "shb_omraden",
  rut_schema = "rutor",
  rut_tabell = "bo_syss_100m_alla_ar",
  utdata_schema = "omradesnycklar",
  utdata_vy = "shb_omraden",
  databas_typ = "vy"
)
```
